repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: rust-check
        name: rust-check
        entry: just rust-check
        language: system
        pass_filenames: false
        files: '(\.rs$|^Cargo\.(toml|lock)$|^crates/)'
