FROM quay.io/strimzi/kafka:1.1.0-kafka-4.3.0
USER root:root
RUN mkdir -p /opt/kafka/plugins/debezium && \
    curl -f -L https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/3.6.0.Final/debezium-connector-postgres-3.6.0.Final-plugin.tar.gz | tar xz -C /opt/kafka/plugins/debezium --strip-components=1
USER 1001
